### ISSUE TITLE
Memory overflow for concurrent CNN predictions

### ISSUE THREAD

**Issue by tashrifbillah** [raun1/Complementary_Segmentation_Network#2]
We are running into memory overflow when attempting to run two concurrent predictions. For each of the predictions, the entire GPU memory seems to be occupied. See the following:

Device 1, GPU 1: capacity 4 GB
Device 2, GPU 1: capacity 32 GB

The same b0 image, when run on two of them, under zero previous load condition, occupies 4 GB, and 32 GB respectively, which is the total GPU memory. Can anyone rationalize this? We guess that since the total memory is being occupied by the first prediction, the second one yields the memory overflow.

In case the error code rings a bell-- 

> 2020-06-04 16:22:41.674241: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

I understand that concatenating the two volumes into one large array and then running prediction overall might help but that is not an option for a volume-wise pipeline. 

cc @SenthilCaesar

**Comment by raun1** [comment]
Hello,

Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR is an environmental problem. Please double check to make sure all the CUDA Toolkit, CUDNN, Tensorflow, Keras are all compatible with each other. 

Keras/tensorflow also blocks all visible gpus as a whole even if the whole memory is not used. I dont think I can diagnose this without more information of what exactly is being attempted.

I guess one solution could be simply blocking each run to one gpu each and then splitting the input into as many concurrent predictions you want at the current time step and calling them all simultaneously.

Also maybe this repository might help - 
https://github.com/yuanyuanli85/Keras-Multiple-Process-Prediction

**Comment by tashrifbillah** [comment]
> Please double check to make sure

Can you take a look at [this](https://github.com/pnlbwh/CNN-Diffusion-MRIBrain-Segmentation/blob/master/environment_gpu.yml)? I appreciate any feedback you might have.

Is `Keras/tensorflow also blocks all visible gpus as a whole even if the whole memory is not used` your rationale for my question-- `Can anyone rationalize this?`

**Comment by senthilcaesar** [comment]
TF would allocate all available memory on each visible GPUs if not told otherwise. Please try the below code . The code gets the list of available GPUs and makes only the first device in that list visible by setting ```os.environ["CUDA_VISIBLE_DEVICES"] = str(DEVICE_ID)```
```
import GPUtil 

# Set CUDA_DEVICE_ORDER so the IDs assigned by CUDA match those from nvidia-smi
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"

# Get the first available GPU
try:
    DEVICE_ID_LIST = GPUtil.getFirstAvailable()
    DEVICE_ID = DEVICE_ID_LIST[0] # Grab first element from list
    print ("GPU found...", DEVICE_ID)

    # Set CUDA_VISIBLE_DEVICES to mask out all other GPUs than the first available device id
    os.environ["CUDA_VISIBLE_DEVICES"] = str(DEVICE_ID)

except RuntimeError:
    os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
    print("GPU not available...")
```

**Comment by tashrifbillah** [comment]
> TF would allocate all available memory on each visible GPUs if not told otherwise.

Hi @SenthilCaesar , you already did that for our pipeline so that is not the problem. The issue I pointed out here is not related to memory of all GPUs, rather one GPU.

**Comment by senthilcaesar** [comment]
Got it . In that case, To my knowledge I don't see a workaround for concurrency on a single GPU.

**Comment by tashrifbillah** [comment]
Hi @SenthilCaesar ,

> TF would allocate all available memory on each visible GPUs if not told otherwise.

Let's say I tell TF to use a single GPU. Is it the default TF/Keras behavior to occupy the whole memory of that GPU?

Do you know if Pytorch differs anyway because I don't see it occupying the whole memory of the said GPU.

**Comment by raun1** [comment]
Hi ,
I was at my internship so didn't realize there were other messages. Was logged into the ancestry github and outlook.

So you are correct pytorch allows you to allocate a % in the gpu memory i learnt from a collegue during the internship. 

So just Googled that issue and it is possible to do the same in tensorflow -

https://www.tensorflow.org/guide/gpu

**Comment by tashrifbillah** [comment]
@raun1 , can you please put the codes within \```python \``` markdown?

**Comment by raun1** [comment]
Please go to the link. You will find it there.
